services:

  supmap-users:
    extends:
      file: compose-supmap-users.yml
      service: supmap-users
    depends_on:
      supmap-database:
        condition: service_healthy
  supmap-incidents:
    extends:
      file: compose-supmap-incidents.yml
      service: supmap-incidents
    depends_on:
      supmap-users:
        condition: service_healthy

  supmap-pbf-downloader:
    image: alpine:latest
    container_name: supmap-pbf-downloader
    volumes:
      - supmap-osm-data:/custom_files
    environment:
      - PBF_URL=${PBF_URL}
      - PBF_NAME=${PBF_NAME}
    command: >
      sh -c "if [ ! -f /custom_files/$${PBF_NAME} ]; then
              echo 'Téléchargement du PBF $${PBF_NAME} depuis $${PBF_URL}...'
              wget -O /custom_files/$${PBF_NAME} $${PBF_URL}
              echo 'Téléchargement terminé.'
            else
              echo 'Le fichier $${PBF_NAME} existe déjà.'
            fi"

  supmap-valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: supmap-valhalla
    restart: unless-stopped
    depends_on:
      supmap-pbf-downloader:
        condition: service_completed_successfully
    ports:
      - ${VALHALLA_PORT}:8002
    volumes:
      - supmap-osm-data:/custom_files
      - supmap-valhalla-data:/valhalla
    environment:
      - PBF_NAME=${PBF_NAME}
      - tile_urls=
      - server_threads=2
      - serve_tiles=True
      - use_tiles_ignore_pbf=True
      - tileset_name=valhalla_tiles
      - build_elevation=False
      - build_admins=False
      - build_time_zones=False
      - build_transit=False
      - build_tar=True
      - force_rebuild=False
      - update_existing_config=True
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8002/status | grep -q 200" ]
      interval: 30s
      timeout: 10s
      retries: 120
      start_period: 5s

  supmap-nominatim:
    image: mediagis/nominatim:4.5
    container_name: supmap-nominatim
    restart: unless-stopped
    depends_on:
      supmap-pbf-downloader:
        condition: service_completed_successfully
    ports:
      - ${NOMINATIM_PORT}:8080
    volumes:
      - supmap-osm-data:/custom_files:ro
      - supmap-nominatim-data:/var/lib/postgresql/16/main
    environment:
      - PBF_PATH=/custom_files/${PBF_NAME}
      - REPLICATION_URL=https://download.geofabrik.de/europe/france-updates/
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/status | grep -q 200" ]
      interval: 30s
      timeout: 10s
      retries: 240
      start_period: 15s

  supmap-gis:
    extends:
      file: compose-supmap-gis.yml
      service: supmap-gis

  supmap-database:
    extends:
      file: compose-database.yml
      service: supmap-database

  supmap-redis:
    extends:
      file: compose-redis.yml
      service: supmap-redis

  supmap-redis-gui:
    extends:
      file: compose-redis.yml
      service: supmap-redis-gui

volumes:
  supmap-osm-data:
  supmap-valhalla-data:
  supmap-nominatim-data:
