services:
  supmap-gateway:
    image: ghcr.io/4proj-le-projet-d-une-vie/supmap-gateway:latest
    container_name: supmap-gateway
    restart: unless-stopped
    environment:
      SUPMAP_USERS_HOST: ${SUPMAP_USERS_HOST}
      CERT_FILE: ${CERT_FILE}
      KEY_FILE: ${KEY_FILE}
      SUPMAP_USERS_PORT: ${SUPMAP_USERS_PORT}
      SUPMAP_INCIDENTS_HOST: ${SUPMAP_INCIDENTS_HOST}
      SUPMAP_INCIDENTS_PORT: ${SUPMAP_INCIDENTS_PORT}
      SUPMAP_GIS_HOST: ${SUPMAP_GIS_HOST}
      SUPMAP_GIS_PORT: ${SUPMAP_GIS_PORT}
      SUPMAP_NAVIGATION_HOST: ${SUPMAP_NAVIGATION_HOST}
      SUPMAP_NAVIGATION_PORT: ${SUPMAP_NAVIGATION_PORT}
    ports:
      - ${SUPMAP_GATEWAY_PORT}:80
    volumes:
      - ./${CERT_FILE}:/app/${KEY_FILE}:ro
      - ./${KEY_FILE}:/app/${KEY_FILE}:ro