services:
  supmap-gateway:
    image: ghcr.io/4proj-le-projet-d-une-vie/supmap-gateway:latest
    container_name: supmap-gateway
    restart: unless-stopped
    environment:
      SUPMAP_USERS_HOST: ${SUPMAP_USERS_HOST}
      SUPMAP_USERS_PORT: ${CONTAINER_INTERNAL_PORT}
      SUPMAP_INCIDENTS_HOST: ${SUPMAP_INCIDENTS_HOST}
      SUPMAP_INCIDENTS_PORT: ${CONTAINER_INTERNAL_PORT}
      SUPMAP_GIS_HOST: ${SUPMAP_GIS_HOST}
      SUPMAP_GIS_PORT: ${CONTAINER_INTERNAL_PORT}
      SUPMAP_NAVIGATION_PORT: ${SUPMAP_NAVIGATION_PORT}
      SUPMAP_NAVIGATION_HOST: ${CONTAINER_INTERNAL_PORT}
    ports:
      - ${SUPMAP_GATEWAY_PORT}:80