services:
  supmap-database:
    image: postgres:17.4
    container_name: supmap-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 30s
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql