services:

  supmap-users:
    extends:
      file: compose-supmap-users.yml
      service: supmap-users

  supmap-gis:
    extends:
      file: compose-supmap-gis.yml
      service: supmap-gis

  supmap-redis:
    extends:
      file: compose-redis.yml
      service: supmap-redis
