services:
  supmap-incidents:
    image: ghcr.io/4proj-le-projet-d-une-vie/supmap-incidents:latest
    container_name: supmap-incidents
    restart: unless-stopped
    environment:
      DB_URL: ${INCIDENT_DB_URL}
      SUPMAP_USERS_HOST: ${SUPMAP_USERS_HOST}
      SUPMAP_USERS_PORT: ${CONTAINER_INTERNAL_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - ${SUPMAP_INCIDENTS_PORT}:80