services:
  supmap-gis:
    image: ghcr.io/4proj-le-projet-d-une-vie/supmap-gis:latest
    container_name: supmap-gis
    restart: unless-stopped
    environment:
      NOMINATIM_HOST: ${NOMINATIM_HOST}
      NOMINATIM_PORT: 8080
      VALHALLA_HOST: ${VALHALLA_HOST}
      VALHALLA_PORT: 8002
      SUPMAP_INCIDENTS_HOST: ${SUPMAP_INCIDENTS_HOST}
      SUPMAP_INCIDENTS_PORT: 80
    ports:
      - ${SUPMAP_GIS_PORT}:80
